-- Analyst A's approach: revenue by market segment
-- Uses L_EXTENDEDPRICE directly, joins through ORDERS to CUSTOMER

SELECT
    c.C_MKTSEGMENT AS market_segment,
    SUM(li.L_EXTENDEDPRICE) AS revenue,
    COUNT(DISTINCT o.O_ORDERKEY) AS total_orders
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM li
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
    ON li.L_ORDERKEY = o.O_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
    ON o.O_CUSTKEY = c.C_CUSTKEY
GROUP BY c.C_MKTSEGMENT
ORDER BY revenue DESC;
